name: dissonance
channels:
  - defaults
dependencies:
  - python=3.9
  - accelerate
  - pytorch
  - matplotlib
  - datasets
  - joblib
  - seaborn
  - urllib3
  - chardet
  - tensorboard
  - peft
  - requests=2.27.1