GENERAL:
  model_name: gpt2-xl
  model_dir: models/pt_models/gpt2-xl

DEVICE_CONFIG:
  cuda_device_order: PCI_BUS_ID
  cuda_visible_devices: "7"
  proxies:
    http: http://localhost:3122
    https: http://localhost:3122

FT_CONFIG:
  dataset_file: dataset/facts/counterfact_dataset/train.parquet
  dataset_path: dataset/facts/counterfact_dataset

  ft_modelH_path: experiments/gpt2-xl/experiment_3_1/ft_modelH
  ft_modelA_path: experiments/gpt2-xl/experiment_3_1/ft_modelA
  ft_modelB_path: experiments/gpt2-xl/experiment_3_1/ft_modelB
  none_path: null

  logging_dir: experiments/gpt2-xl/experiment_3_1/logs
  
  max_length: 128
  start_sample: 0
  sample_size_1: 2000
  sample_size_2: 1000
  training_lr_1: 0.010
  training_lr_2: 0.010
  num_epochs_1: 5
  num_epochs_2: 10
  batch_size: 32
  eval_every_n_epochs: 10
  historical_file_pathA: experiments/gpt2-xl/experiment_3_1/historical_dataA.pkl
  historical_file_pathB: experiments/gpt2-xl/experiment_3_1/historical_dataB.pkl

HISTORICAL_FEATURES_CONFIG:
  patterns:
  - \b\w+(?:\.mlp\.c_fc)\b
  - \b\w+(?:\.mlp\.c_proj)\b

  threshold:
  - 20000
  - 40000
  - 60000
  - 80000
  - 100000
  - 120000
  - 140000
  - 160000
  - 180000
  - 200000


EXPERIMENT_CONFIG:
  title: experiment_3_1
  n_rep: 1
  n_folds: 5
  seeds:
  - 46

  results_dir: experiments/gpt2-xl/experiment_3_1/results

  strategies:

    free_A:
      inverse: False
      norm: False
      rnd: False
      hist: historical_file_pathA
      gen_hist: none_path

    busy_A:
      inverse: True
      norm: False
      rnd: False
      hist: historical_file_pathA
      gen_hist: none_path

    free_B:
      inverse: False
      norm: False
      rnd: False
      hist: historical_file_pathB
      gen_hist: none_path

    busy_B:
      inverse: True
      norm: False
      rnd: False
      hist: historical_file_pathB
      gen_hist: none_path

    spec_B:
      inverse: True
      norm: False
      rnd: False
      hist: historical_file_pathA
      gen_hist: historical_file_pathB

    rnd:
      inverse: True
      norm: False
      rnd: True
      hist: historical_file_pathA
      gen_hist: none_path
