GENERAL:
  model_name: gpt2-small
  model_dir: models/pt_models/gpt2-small

DEVICE_CONFIG:
  cuda_device_order: PCI_BUS_ID
  cuda_visible_devices: "7"
  proxies:
    http: http://localhost:3122
    https: http://localhost:3122

FT_CONFIG:
  dataset_file: dataset/facts/counterfact_dataset/train.parquet
  dataset_path: dataset/facts/counterfact_dataset

  ft_modelH_path: experiments/gpt2-small/experiment_2_3/ft_modelH
  ft_modelA_path: experiments/gpt2-small/experiment_2_3/ft_modelA
  none_path: null

  logging_dir: experiments/gpt2-small/experiment_2_3/logs
  
  max_length: 128
  start_sample: 0
  sample_size_1: 10000
  sample_size_2: 2000
  sample_size_3: 1000
  training_lr_1: 0.0005
  training_lr_2: 0.0010
  num_epochs_1: 5
  num_epochs_2: 10
  batch_size: 32
  eval_every_n_epochs: 10
  historical_file_path: experiments/gpt2-small/experiment_2_3/historical_data.pkl

HISTORICAL_FEATURES_CONFIG:
  patterns:
  - \b\w+(?:\.attn\.c_attn)\b
  - \b\w+(?:\.attn\.c_proj)\b
  - \b\w+(?:\.mlp\.c_fc)\b
  - \b\w+(?:\.mlp\.c_proj)\b
  threshold:
  - 2000
  - 4000
  - 6000
  - 8000
  - 10000
  - 12000
  - 14000
  - 16000
  - 18000
  - 20000

EXPERIMENT_CONFIG:
  title: experiment_2_3
  n_rep: 5
  seeds:
  - 46
  - 16
  - 5
  - 114
  - 1220
  results_dir: experiments/gpt2-small/experiment_2_3/results

  tot_neurons: 82944

  strategies:
    free:
      inverse: False

    busy:
      inverse: True